name: Controle Luminosite Kiosk

on:
  schedule:
    - cron: '0 6 * * *'  # Matin
    - cron: '0 18 * * *' # Soir
  workflow_dispatch: # Pour tester manuellement

jobs:
  update-brightness:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4 # Passage en v4

      - name: Installer Node.js
        uses: actions/setup-node@v4 # Passage en v4
        with:
          node-version: '24' # Passage en Node 24 pour le futur

      - name: Executer le script
        env:
          API_KEY: ${{ secrets.KIOSK_API_KEY }}
          DEVICE_ID: ${{ secrets.KIOSK_DEVICE_ID }}
        run: node regler_kiosk.js
